name: Makefile CI

on:
  push:
    branches: [ "test-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: poetry install --only=main

    - name: Run lint and test
      run: make test
